### ISSUE TITLE
License

### ISSUE THREAD

**Issue by egelja** [apkizer/hy3.js#3]
Hello!

I'm looking for an HY3 file parser, and yours is the most complete out of any I have found. However, it doesn't have a license, so it is current licensed under "All Rights Reserved" with you, @apkizer, holding those rights, meaning I cannot use this library in any other project.

Could you please put a `LICENSE` file in your repo with something like the [MIT License](https://choosealicense.com/licenses/mit/)? It will take only 30 seconds; you can do it from the Github web editor.

Thank you very much! I really appreciate all the hard work you must have put into this project.

**Comment by colddiver** [comment]
Hello,

I'm not the owner of hy3.js. I did write a hy3 parser but it is located athttps://github.com/colddiver/sdif-parser and it is released under the MIT license.

Étienne

**Comment by apkizer** [comment]
Hi, sorry for the late reply. I'll add an MIT license shortly. Hopefully
it's not too late! Please PR if you add anything :)

Alex

**Comment by apkizer** [comment]
I’ve added the MIT license. Also, I’ve migrated the project to my current GitHub account: @kizerkizer
